### PR TITLE
kickstart/angular file overview

### PR DESCRIPTION
**Pull request by kaseyjcowley**
@erikthedeveloper 
Have a look-see over these Angular kickstarter files. 
1. We've got a basic build setup with Gulp:
   - Linted, concated, minified JS
   - Compiled LESS files
   - A default 'watch' so we don't have to do anything when we change files
2. A good working Angular JS structure
3. A good LESS/CSS setup

Let me know what your thoughts are on storing the final JS/CSS files in a dist/assets/js and dist/assets/css folder for inclusion into our actual app. That seems to be the structure people like to use with Gulp when building stuff.

### CODE REVIEW

**Comment by erikthedeveloper** [comment]
And the tests still passed! ;)

**Comment by erikthedeveloper** [comment]
Awesome man. I'll take a closer look when I get a chance, but it looks like we are about ready to rock.

I'll start in on our BaseApiController and other backend hoopla. Feel free to comment on lines/commits

**Comment by erikthedeveloper** [comment]
Pulled down... rebased... push -f     merging!

**Comment by kaseyjcowley** [comment]
@erikthedeveloper 
Have a look see at the awesomeness of Angular's $resource module. I added a User frontend resource that ties up directly to our Users route in Laravel. It's freaking sweet.

**Comment by erikthedeveloper** [comment]
I feel like I'm crazy.... haha. I'm not seeing it. What file/dir?  You are literally getting ready to head out on your trek aren't you? Yeah, I guess that means I'm done for the day ;) Enoy.

**Pull request merged**
